- name: Create zone file
  copy:
    content: ''
    dest: /var/lib/knot/{{zone}}.zone
    force: false
    group: knot
    owner: knot
    mode: 0660
  register: create_zone

- name: Check if zone is initialized
  shell: grep '\s\+SOA\s\+' '/var/lib/knot/{{zone}}.zone'
  register: has_soa
  changed_when: has_soa.rc != 0
  failed_when:
    - has_soa.rc != 0
    - has_soa.rc != 1

- name: Initialize zone
  when: has_soa.changed
  shell: |
    knotc conf-begin
    knotc conf-set zone.domain {{zone}}
    knotc conf-commit

- name: Create SOA and NS records
  when: has_soa.changed
  shell: |
    knotc zone-begin {{zone}}.
    knotc zone-set -- @ 7200 SOA {{knot.ns}}. admin.pupy.cloud. 0 86400 900 691200 3600
    knotc zone-set -- @ 21600 NS {{knot.ns}}.
    knotc zone-commit --

- name: Create NS A record
  when: has_soa.changed and zone == knot.ns.split(".", 1)[1]
  shell: |
    knotc zone-begin {{zone}}.
    knotc zone-set -- @ 3600 A {{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}
    knotc zone-commit --

# - name: Reload knot
#   shell: knotc reload
#   when: create_zone.changed
