- name: Install Knot
  become: true
  dnf:
    name:
      - knot
    state: present

- name: Ensure knot config directory exists
  become: true
  file:
    path: /etc/knot
    recurse: true
    state: directory

- name: Start Knot Authoritative
  become: true
  systemd_service:
    name: knot
    enabled: true
    state: started

- name: Configure Knot Authoritative
  become: true
  block:
    - name: Configure Knot
      template:
        src: knot.conf.j2
        dest: /etc/knot/knot.conf
        owner: knot
        group: knot
        backup: true
      register: knot_conf

    - name: Check Knot config
      command: knotc conf-check
      notify: restart knot
      when: knot_conf is changed

  rescue:
    - name: Restore backed up config
      copy:
        remote_src: true
        src: '{{knot_conf.backup_file}}'
        dest: /etc/knot/knot.conf

    - name: explode
      fail:
        msg: failed to do the knot thing
  always:
    - name: Delete backup
      file:
        path: '{{knot_conf.backup_file}}'
        state: absent
      when: knot_conf is changed
#
# - name: Reload knot
#   shell: knotc reload
#   when: create_zone.changed

- name: Provision zones
  loop: '{{knot.zones}}'
  include_tasks: init_zones.yml
  vars:
    zone: '{{item}}'

- name: Install dnspython
  register: init_zones
  pip:
    name: dnspython
    state: present

# Why does nsupdate not work until after it restarts?
- name: Restart knot
  when: init_zones.changed
  service:
    name: knot
    state: restarted

- name: Create DNS records
  loop: '{{knot.dns_records}}'
  nsupdate:
    key_name: '{{item.key_name | d(knot.key[0].id)}}'
    key_secret: "{{(knot.key | selectattr('id', '==', item.key_name | d(knot.key[0].id))) | map(attribute='secret') | first}}"
    key_algorithm: "{{(knot.key | selectattr('id', '==', item.key_name | d(knot.key[0].id))) | map(attribute='algorithm') | first}}"
    server: "{{item.server | d('127.0.0.1')}}"
    port: '{{item.port | d(knot.interfaces[0].port) | d(53)}}' # default to 53?
    zone: '{{item.zone}}'
    record: '{{item.record}}'
    value: '{{groups[item.group] if item.group is defined else item.value}}'
    type: '{{item.type}}'
    state: present
