creation_rules:
  - path_regex: profiles\.yaml
    encrypted_regex: '(env)|(repo)'
    pgp: >-
      870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35

  - path_regex: .+\.sops.ya?ml
    encrypted_regex: 'secret|password|token|email|auth_key'
    pgp: >-
      870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35

  - path_regex: infra/.env
    encrypted_regex: '(?i)(password|secret|token)'
    pgp: >-
      870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
