- name: Add PostgreSQL rpm gpg key
  rpm_key:
    key: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL
    state: present

- name: Add PostgreSQL repo
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Check if crb is enabled
  command: /usr/bin/crb status
  changed_when: false
  register: check_crb

- name: Enable crb
  command: /usr/bin/crb enable
  when: "'disabled' in check_crb.stdout"

  # TODO: the rpm_key thing makes an interactive "importing gpg key is this ok y/n" thing
  # and idk how to make it not do that in this step
- name: Check if PostgreSQL dnf module is disabled
  shell: dnf module list postgresql --enabled --assumeyes
  register: pg_dnf_module
  changed_when: false
  failed_when: false

- name: Disable the built in PostgreSQL module
  command: dnf -qy module disable postgresql
  when: "'postgresql' in pg_dnf_module.stdout"

- name: Install PostgreSQL
  dnf:
    name:
      - postgresql17-server
      - postgresql17-devel
    state: present

- name: Install psycopg2
  pip:
    name: psycopg2-binary
    state: present

- name: Check if PostgreSQL is initialized
  stat:
    path: /var/lib/pgsql/17/data/postgresql.conf
  register: pg_data

- name: Initialize PostgreSQL
  command: /usr/pgsql-17/bin/postgresql-17-setup initdb
  when: not pg_data.stat.exists

- name: Bind to all interfaces
  lineinfile:
    path: /var/lib/pgsql/17/data/postgresql.conf
    regexp: 'listen_addresses ='
    line: "listen_addresses = '*'"
    state: present
  notify: restart postgres

- name: Start PostgreSQL
  service:
    name: postgresql-17
    enabled: true
    state: started

- name: Configure pg_hba.conf
  include_tasks: hba.yml

- name: Create databases
  include_tasks: db.yml

- name: Create users
  include_tasks: users.yml
