knot_resolver:
  interfaces:
    - ip: 192.168.5.3
      port: 53
    - ip: 0.0.0.0
      port: 5302
  # management:
  #     ip: http+unix://127.0.0.1
  #     port: 5000
  forward:
    - subtree:
        - pupy.cloud
      servers:
        - 127.0.0.2
      options:
        authoritative: true
        dnssec: false
knot:
  interfaces:
    - ip: 0.0.0.0
      port: 5301
    - ip: 127.0.0.2
      port: 53
  zones:
    - pupy.cloud
    - internal.pupy.cloud
    - box.pupy.cloud
  key:
    - id: admin
      algorithm: hmac-sha256
      secret: ENC[AES256_GCM,data:3JMeNe9UCvoZqro8MqNRcwgyjWIGY3XEXwg8Ow4HAXZx82I0TIecdLO5kf4=,iv:u/rxAxH9mEJEiFicJLoc6xTgh2ffeslGAEfb5+mJZQw=,tag:LJ06q5hGdPEC0GKzAQrXtg==,type:str]
  queryacl_address:
    - 192.168.8.0/24
    - 127.0.0.1
  ns: ns.pupy.cloud
  dns_records:
    - type: A
      zone: pupy.cloud
      record: sonarr-iac
      group: gateway
      # server: 0.0.0.0
      # port: 5301
    - type: A
      zone: pupy.cloud
      record: radarr-iac
      group: gateway
    - type: A
      zone: pupy.cloud
      record: prowlarr-iac
      group: gateway
    - type: A
      zone: pupy.cloud
      record: plex-iac
      group: gateway
    - type: A
      zone: pupy.cloud
      record: adguard-iac
      group: gateway
sops:
  lastmodified: "2025-06-26T23:29:37Z"
  mac: ENC[AES256_GCM,data:Zxi5Vbq8YhK898idC9tdSDHcIjo7hEt0WozpI7YLT++TjZe4ql49q+s6Hl4F4mTbLkS1besCu25beLxFHNrRvvSLCpzvMCUM0fCcueamgzhK+UdWzSd5zONEdOHUqzijNAt3a6RzA/08YcEyw8V8B2hrZ719Zsn+gHNzImZOK6c=,iv:y0zjZttkx1jqVc6yBEQtS/6/D6Vi0CtlbcVDYk5gidw=,tag:SDK3gtVsasDFWl3DUh6Gbw==,type:str]
  pgp:
    - created_at: "2025-06-26T23:29:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4Dlw80gGBdP4gSAQdATEC4Kv/XhZimwE+vGtSRUJ0B12N1ZHkH5RqUiTmjXX8w
        4XLOUDmjXPNonBA8xQTWxRzMe8RQU5bs296vdnDuuWC2BTgrQ2tIe+BbAP44/Yf4
        1GgBCQIQCUe9oRemSIJP2OGgPnH1ASFhVrfkwuWcpfC4/hAprOficDdBAk9hjELD
        aZx8WaKEjwgCM/afw0aVGYLtbOxBP31fvxlF/PelBPiMmNaChcMyHMdUFOC5fjjP
        rRdO52NH8wCXgQ==
        =J5aa
        -----END PGP MESSAGE-----
      fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
  encrypted_regex: secret|password|token|email|auth_key|wireguard_
  version: 3.10.2
