knot:
    interfaces:
        - ip: 0.0.0.0
          port: 5301
        - ip: 127.0.0.2
          port: 53
    zones:
        - pupy.cloud
        - internal.pupy.cloud
        - box.pupy.cloud
    key:
        - id: admin
          algorithm: hmac-sha256
          secret: ENC[AES256_GCM,data:3dD9MYS+H07FPP6Lfmu861DZmznC75Yd4Gyw8M7RtKBuqzUJeixXnf/T9FI=,iv:NDS26twC7Zlsd6U+oODIff1lapRnHgmQpoMoIFmTEXk=,tag:AyakeDzTMU3U7+ziCutPEA==,type:str]
    queryacl_address:
        - 192.168.8.0/24
        - 127.0.0.1
    ns: ns.pupy.cloud
knot_resolver:
    interfaces:
        - ip: 0.0.0.0
          port: 5302
    management:
        ip: 127.0.0.1
        port: 5000
    forward:
        - subtree:
            - pupy.cloud
          servers:
            - 127.0.0.2
          options:
            authoritative: true
            dnssec: false
sops:
    lastmodified: "2025-06-02T02:28:08Z"
    mac: ENC[AES256_GCM,data:6mRQ42nk2W0Kr+i7Ns72OYsxl5SbuZEpFTQHa5npABeCILkXz+Xr5moiKmu+IVUXIkZih6lBu2Gcfp3qNAaHuJT+31KF5yFsYlkP2CEt+Eyr04izY+Zr9TrZmYy093ed4xUZ06CdUFySEj85bn5RMijj/LlNO5KT/1W2qwQNcE8=,iv:munpMXR3XYhrvRManO2TB+0Ol2GM97Zsyo4++TJnhtc=,tag:1GMIs+6yPvEMoQlnt/IV4A==,type:str]
    pgp:
        - created_at: "2025-06-02T02:28:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdA9Agau+xzXhnidMZadoW2UorNJBX0c+vqngNV9r/l/jkw
            wP3EagZK/harkt9WEGKauxf1iDSseu+yby6jhCot6auXerfN3fMGxL8ncAvvrQDH
            1GgBCQIQR0ecprLmGdTRKEFo+AIjjAjbk6nnF9iOOCHoDgu0s+aFMmu+glxHFINV
            +LEZTgPTs5KlhX3kcpjGDZ7zZfmwvcEv0myIIlxHK2n/HpDghoA2o/QsyqMx2T/G
            MLCx/NOlh9/0Mg==
            =NTk/
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: (secret)
    version: 3.10.2
