knot:
    interfaces:
        - ip: 0.0.0.0
          port: 5301
        - ip: 127.0.0.2
          port: 53
    zones:
        - pupy.cloud
        - internal.pupy.cloud
        - box.pupy.cloud
    key:
        - id: admin
          algorithm: hmac-sha256
          secret: ENC[AES256_GCM,data:vVTEa0z9ki80K8GTRj2YEs5ZzlmMPKD1Rn494603ejb9Ema0ToRVF9e65FY=,iv:3OSq3s/j3zAacBfBabt4L2iyfl/ZN60ks+TABD9DoVw=,tag:v2NfCcCvXfaKTAiyY2lh8w==,type:str]
    queryacl_address:
        - 192.168.8.0/24
        - 127.0.0.1
    ns: ns.pupy.cloud
knot_resolver:
    interfaces:
        - ip: 0.0.0.0
          port: 5302
    # management:
    #     ip: http+unix://127.0.0.1
    #     port: 5000
    forward:
        - subtree:
            - pupy.cloud
          servers:
            - 127.0.0.2
          options:
            authoritative: true
            dnssec: false
sops:
    lastmodified: "2025-06-06T22:22:49Z"
    mac: ENC[AES256_GCM,data:7NTdKXM5K+1Vjmyamd+FnBo3eZAB+b4TJpYC+19f87ZcOCou6i3Oii2wxzVej+q24WYUwaHZD1MN+0uqrvpArislt0NtoNn+2KkR+vaFiZYAc85jwnk5XSfRimtkj8CFiCb14x92uYk5EtuOdBb7ERlwxGGJha5lYyQbAXhbInw=,iv:i4SjiolyRTRwNkOw9g1E+EJBWsy0XSJG4iYDEOpDVM8=,tag:BHejt2gifDeaE/RliApjHw==,type:str]
    pgp:
        - created_at: "2025-06-06T22:22:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdAvJPEY76j2xR5YlG/XHLeUNu9CmJARCPOaHg8q8pxxCEw
            7oCk+B47XRZu4AT+xrV06jGyLGfkljg6wrZ1PJqBYB0a3iksdTfgVdZeGrlFUmff
            1GgBCQIQYMoxHB9MRVS0hqs5vYQBxaziH6OpROaeYjXbF1U2NQjpHF9kEmZ6dXM0
            7a9oHv/ZnO7lo+9Do1vExfz0m8239Pp8DLIciJAs1oViyWcvMNpaQM9zSt8Vv+J3
            n/yNKjIkOBKADw==
            =IrAn
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: ^(secret)$
    version: 3.10.2
