letsencrypt_email: ENC[AES256_GCM,data:aNB1gNKXM7yebO1nJPE=,iv:ePHqsMpAAZ7QVtEYCReAkaIeFXYUWsBqhGrgovg9hHM=,tag:H2cbqBAp59Xf8fR1l5TO3A==,type:str]
reload_haproxy: true
certbot_cloudflare_api_token: ENC[AES256_GCM,data:xK/i/YKL/sp5CaWoiS4IE1hOT3Sy59aJzElXMSpu4NLGUbSTNFXyoA==,iv:kuW6q3xZA/SKuzX3NCsLR9f6mFTkQrALEJqybKOqdKE=,tag:yEwb07+EJTNjfR3I1xok+Q==,type:str]
certificates:
    - name: pupy.cloud
      domains:
        - pupy.cloud
        - '*.pupy.cloud'
        - '*.test.pupy.cloud'
reverse_proxy:
    https:
        - name: testing
          domain: test.pupy.cloud
          backend_group: dns
          backend_port: 8000
        - name: sonarr
          domain: sonarr-iac.pupy.cloud
          backend_group: sonarr
          backend_port: 8080
        - name: radarr
          domain: radarr-iac.pupy.cloud
          backend_group: radarr
          backend_port: 8080
        - name: prowlarr
          domain: prowlarr-iac.pupy.cloud
          backend_group: prowlarr
          backend_port: 8080
        - name: qbittorrent
          domain: qbittorrent-iac.pupy.cloud
          backend_group: qbittorrent
          backend_port: 8080
sops:
    lastmodified: "2025-06-09T22:09:54Z"
    mac: ENC[AES256_GCM,data:7PskryvUCacreO0Hu2oVjp/Av648/p4DaoPuczv4bJxaWURCV8zLTi3DZ2OkATEzFI54uZ/4iX0rNZIX6Fnj868PitKN1vp3+1gkJ6qauET8ex4I0AqcxXWaX/E9+1Tytj3aCWK7XjlW0zBLENtGcKbdiF797jfKM49Zvu8DLiA=,iv:8dupB0eIksgJqJDNHpPqv1pZOn18619X5zdELDCnLXY=,tag:DEbLB7Mwev2bxBEiQkcL/g==,type:str]
    pgp:
        - created_at: "2025-06-09T22:09:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdASbqaFrPeKGPsXcAXVJD3Qu0pjaTkPoV09ncsTh3wJ34w
            n7+JVZ/1XDD/2RLictRFyhZxRx3CUOqYgAIR6VxdbwULja+XUPhNoHP3ma4qa5TX
            1GgBCQIQ+Ek6lhP1+gzz6rAOHv9fmcx44BllYgSvURnlnDOAPc4gSgnp6Lu/sH3B
            +chjcBv0gySIxBb6BPyqSpmWLoYtLM09G8uTCGBHF8WpG1aabyoqNhjpCOK8xmSN
            xJDlEKCg/lyMMg==
            =9Ccg
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: secret|password|token|email
    version: 3.10.2
