postgres_users:
    - name: terraform
      password: ENC[AES256_GCM,data:N3z7VLUyFwgmSJQ7KD13JQVDMV3KgA==,iv:PMaJuCeBDmXAKPSIdEHHxVkZ7m84G3V3hfIKXpXTZYw=,tag:HYAFjPrgeW2U00DoDfrA9Q==,type:str]
postgres_databases:
    - name: terraform
      owner: terraform
sops:
    lastmodified: "2025-06-08T19:37:33Z"
    mac: ENC[AES256_GCM,data:I7t8oURFrGbs5mPba6qaD0OlszcuyktlQJ0MyN1gXEj3iVZFpDB/I/dUktkGaUbBZleFSKaEoLBxz4wSGzDTAZiL79c641DKIIcbo430smFL8En2IpQ3czrTfaaADnX5xOxnKOIzz7+Z65tPKuIKNWKmu4TZA67UfiDtqc31y2M=,iv:t3TIpfgoBaV79FMgCadLYjAgs3cdRfuqny9bU0lUj/I=,tag:NV/NPRBXIdN9rElOwpcTrw==,type:str]
    pgp:
        - created_at: "2025-06-08T19:37:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdAxhauqP3vXeoAqk0tcXDDEm95RKb1+ZMwaoYcAwWuRmYw
            rxyJI4KP7Af94CytRwzpv9y9pXBK48atvwq/434nyaJUytkH9+IlmVzkmyQExZMX
            1GgBCQIQpkhDSV0e2hkhBwrJKOjNI+Za5Uwsj+/NqHGkRbUn7ohJAwOvmDxi++sE
            bEeB64EOISkJsGRDLvzlBLBpJb+FvPgyyht72QFpV6VIafEQXEzK4Gqurj5598gc
            7Ea3aSeNOe5c4Q==
            =BVFT
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: secret|password|token|email
    version: 3.10.2
