passwords:
    terraform: ENC[AES256_GCM,data:5/umcUWdC14djzCY4tRta0KdE/EQUQYYORDGRheRY4hVTx9e/36tJz1LwziEctIWhPLXosbcK5oB1BKjalO8diwggKRcCpWMLJ7BXq/ZKVSCxZwzfrX+tZOoqd+bDU31++njPe6Bc5QOXP4nbfEIGdQbK5nbBbL7Jd5JuCvH3U/WEQGptg==,iv:lDLDjGIbFSeytW4mwoyfxoy2Belem+d4UHMT8Yky3eI=,tag:ytUdtCRI2hrSEmJHAwEpdg==,type:str]
sops:
    lastmodified: "2025-06-07T19:20:05Z"
    mac: ENC[AES256_GCM,data:zZrxQ6r38w2fyRwO8FJE14ysrbY6Q/DoDMQ4S9ND+6+17ICNS4+DF0vxqjj4Ag8hv5M4FdeDHgMzcPYmS2OFtfOEB8n+qYHPCU/CynGbDGLeAkekt7C2EAvomWXIUbaIR5hzoO8KumQLmOSeQZNSct+ABAmz6ebj82PFnac9cdk=,iv:oyoS8Tafq8I9ZAq7+EgH29r2Q3hiZuJ50ii6bk6Blno=,tag:nvvjOvHlfCQyCEFsXHxbLA==,type:str]
    pgp:
        - created_at: "2025-06-07T19:20:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdAOkX/xRbJliOwDzigSEBH/iItaxzscfCqdiaWikO263gw
            DMJNfXsObj4EqJHgfmapx+i+fXqQ7/ZH/k9ac+P7pUpVPsa+24yOMOb/ilcP1hJE
            1GgBCQIQEZieChRfi0AmGE2CWppDgYH3c93J+0r3RA23yzzlbouhRVL98YerRIA0
            K69e4QNix2ZO0wBruEY47A3Af6AeTW3c+qtuGZr4rGE2sVAp64aH7jHSWxHy9Soc
            IBaiWMDfmAIt6w==
            =Ea2E
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: secret|password
    version: 3.10.2
