# US-VA#91
wireguard_private_key: ENC[AES256_GCM,data:i4FOLmkN0lkPX8ympu6OxRRQepbUrmoTu8Pt/7xA6MZhelgAXrnqAtSEeOI=,iv:kiMygDgjCXVSNulRYsuS8K5mmj3cMT1vuQ9dTEF+qCc=,tag:5x7MiGlCUnOrqwLuy668vQ==,type:str]
wireguard_public_key: ENC[AES256_GCM,data:eiI+0ET5ZTBeQvzw1+40baN9lBzzlT3mDzaaA5scX+6C/PjGk9xjw1SxWYI=,iv:tZnmuX0r3Nk0qJApcjc1P3FbWwV9GqPTJl3vJTJqvbM=,tag:JqQ98IRygBoZ8fvXbIwgGg==,type:str]
wireguard_endpoint: ENC[AES256_GCM,data:ptIrnJqUNpeKY/oMqWZo7xx+Vg==,iv:0a+jHmpHhwhDFBNtx3xo8gF8lm65oyev9YH04/ZP1tI=,tag:/9F43Dm7gW173OYPKhZXNg==,type:str]
wireguard_address: ENC[AES256_GCM,data:VeeybprIrohW5H4=,iv:Yd6WtbJdAsgEFwDM91Cpg2oZc2GvucrbxxC0tZk4Yvs=,tag:QBKiA7MlPqNnKxdAcmbEXw==,type:str]
wireguard_dns: ENC[AES256_GCM,data:OM7V39aunrc=,iv:F3JJHitj/tzwUGeu60UGI8D+GlnV5hlyhvXYAL8KHWE=,tag:pgfUAYm01fNS5ior8b2VDw==,type:str]
qbt_port_updater_username: admin
qbt_port_updater_password: ENC[AES256_GCM,data:G+BUgwbIZF8DfQ==,iv:5oNIESTyfM06YAKHNEWBI6PCMhIBFxir5oPa+LocoX4=,tag:jPxISg6TxSRjMJde8oif4g==,type:str]
qbt_port_updater_url: http://localhost:8080
sops:
    lastmodified: "2025-06-17T21:21:38Z"
    mac: ENC[AES256_GCM,data:kr1X5cqPYm8GulxmTy4VK69Qxcntt3X1rY+rJ3CBqoGufC2ROZGJiUY2jDVZGKFxGnFYD8jD8JLUNznifctjDA613K+07FMoZ32gHyVHr+kX4m2qg9+mzmluZLCAijBBdYNZVbRdr22NisECmXBqOY0CbfFSHDQeIbsbyjtAMe8=,iv:9euJvKrT95xmLK5yYGfzRqrBdvnpoFW+4owzdEY3cd4=,tag:y4QiUCF2R1QZWJMYHq+w7A==,type:str]
    pgp:
        - created_at: "2025-06-17T21:21:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdACqcUEiBRVlIVL9h2PiSNN6WcVfa72nMhPnVBP2POtTww
            kdOf4ejUp7yUOaD6KCGKTkOOlBXfJly/sp3UkaqNOWOIX8Xwf42fXU6kzGsV/kGK
            1GYBCQIQq4SW0yy83e+yt+EstGijvG3t4g9fUnynwx6ts0Fz2FCaVzqt9kgMkeRC
            tBm47jHLPirVVW1tUT2wU8+Z3qo/125fgbaz1ywFLpmohkx5ycmMLMOC57oLie9b
            3Nzkybt6krU=
            =jAm1
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: secret|password|token|email|auth_key|wireguard_
    version: 3.10.2
