tailscale_auth_key: ENC[AES256_GCM,data:8hy0Tm8QkK7q/zg3yqrok0j7axA12xgN96vee5HoZ1SHHABX//FqrMy/slzVR/ds7JZPJtEXCJjJmpsdppQ=,iv:AxznwlOqDqURFciRdicmfx0qBcRbzgJ/wSPHUwpx8tk=,tag:9ojY5IZ7AyJ+ncAJc2OEgA==,type:str]
sops:
    lastmodified: "2025-06-11T22:41:47Z"
    mac: ENC[AES256_GCM,data:/tZHVmTubigHKO3QpGkiBOEw2Ebx3xuZESWec3dlJbYoorBuAyyNtg3HgX9XxS3O+yJ27/n6wxbPd5ypLVwGoruvPAsfWCNqbjbtGbVHzSlC+WZzjAMoC35zlP0IzZCrpDUpiEX7J31v+m6HFEUvIZ6ueil1twXpPPVseHRdKiY=,iv:YpLYdv8xsgLqxsFex0jldLeuFnMJM4nv+py+yLlsxG4=,tag:vZnyiRn3Nv1aHkiBzhnODg==,type:str]
    pgp:
        - created_at: "2025-06-11T22:41:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdAGCpJzlEdYsIH460NrkI8nC2Mw6gSoLu1uFqarL4xvhsw
            Nudvh7KMngg10qAAwKXUNKjzZ/v+sRowkbWJgn1/1SfN6qrKc0Hfho93LJblKHO7
            1GYBCQIQYPqsJ6XE6Sl1VWAlTpXgpfWxMN7ZGn40RAZ6zv6+QQhZojw2nrZ448Wd
            6pdB6DVYwl7oHtf9vzC6QX0udYdACCcVUNspP1q9yryof8TKHgkgP5zfU2SKlNFk
            De4sJGM1MhY=
            =sT97
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: secret|password|token|email|auth_key
    version: 3.10.2
