- name: Update packages with dnf
  become: true
  dnf:
    state: latest

- name: Install epel
  become: true
  dnf:
    name: epel-release
    state: present

- name: Install basic packages
  become: true
  dnf:
    name:
      - vim
      - htop
      - python3
      - python3-pip
      - grep
      - dnf-automatic
      - tar
      - file
      - tmux
    state: present

# TODO: why does this time out???
# - name: Enable unattended upgrades
#   systemd_service:
#     name: dnf-automatic.timer
#     state: started
#     enabled: true
