# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config.json
version: "2"
global:
    initialize: true
    scheduler: systemd
mixins:
    b2-cloud:
        base-dir: /etc/resticprofile
        password-file: password.txt
        repo: ENC[AES256_GCM,data:O3CVzSxmVmhAGLlKhxbezkPkFq6MHB+wkvj4zxW+1td0z4cFpybeZ5cQs5dO,iv:7utb9R1MK9HC0403+S0kpJ2lPIkP9THfqvcZvPo0uKo=,tag:sxZAqOracEoTy65NyedRpA==,type:str]
        env:
            RESTIC_COMPRESSION: ENC[AES256_GCM,data:YmaJ,iv:IdY/Z3PRPlUyjR3vk4TGQ0uPjiie+VVZJHxqqaIhiH4=,tag:i6LqvORLWmGs48euqxA4OA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5cBh0q5mXiWhrIWmos+onTPAF46V4fZMww==,iv:WWx+OZ4mReMg25GW1WcWPZxLPOS8nn6XZrgbsO0KCNw=,tag:Z9vnYOpsGLoUsc5R6HfaTQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+CKHTlgb2ggzasnXDMMNo7dxktFbVnY7S3pPQ/Tn8A==,iv:f59h2JYwaoCfXPPqRtx9tleU3qnL4E7jtlsGv1qsEgk=,tag:tpAarW+REUI0z+Lu/DStkg==,type:str]
    base-profile:
        backup:
            host: cloud
            one-file-system: true
            exclude-caches: true
            exclude-file: excludes.txt
            no-error-on-warning: true
            schedule-permission: system
        retention:
            before-backup: false
            after-backup: true
            keep-daily: 7
            keep-weekly: 4
            keep-monthly: 6
            keep-within: 3h
            prune: false
            host: true
profiles:
    netbird:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - netbird
            schedule: weekly
            source:
                - /home/ben/docker/netbird-server/backup
            run-before: |
                pushd /home/ben/docker/netbird-server
                mkdir -p backup/management
                cp docker-compose.yml management.json turnserver.conf backup
                docker compose stop management
                docker compose cp -a management:/var/lib/netbird/ backup/management/
            run-after: pushd /home/ben/docker/netbird-server docker compose start management rm -rf backup
    traefik:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - traefik-public
            schedule: daily
            source: /etc/traefik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T15:33:55Z"
    mac: ENC[AES256_GCM,data:UeOpg7IdEWo+sjKYkdJ6xgjO9WF9wi5XmfL48Q7bcjkD3lEOHDElPKjkLNDV00GlEPjDuBX2Xino8169ldOPaMRPe9Ery28QY8XaTMrTQFmS+8ilbrbZrpaVki2XgiZfkWwpnv6qW/4bjHUdF3sqSM7yrlrxnWTQ0Ir3QXAX764=,iv:tjEz5DSzrvlt/ONo+Uo6FYYVGjniJTZHcUI+1didDM0=,tag:7A/Phca/3mzO6A5C9wOv2A==,type:str]
    pgp:
        - created_at: "2025-01-28T00:39:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdA3KIYqNNL+OFxtuESisjSLA/lcAzsRznvfum6AZ07kgAw
            0cHg/1ZREgUeOPkCDfE+M+ELpI+CbBadG+ex2TpW/fvFHb1kt1myK8FWQMu/ycL7
            1GgBCQIQVcsnp0DGNqbb1eWnfcEyTmKHyWHRO+vC2AhLDEiI4RNW15aViowcvnKJ
            tsDYqMTKDeUmsy6A4yv4x94fJfgJ4bzVRRgPnz0JbNWI0TPIZlUWnUJ51nDzBHZ3
            lSqNfvd3drzBqg==
            =vg7W
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: (env)|(repo)
    version: 3.9.4
