# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config.json
version: "2"
global:
    initialize: true
    scheduler: systemd
mixins:
    b2-cloud:
        base-dir: /etc/resticprofile
        password-file: password.txt
        repo: ENC[AES256_GCM,data:O3CVzSxmVmhAGLlKhxbezkPkFq6MHB+wkvj4zxW+1td0z4cFpybeZ5cQs5dO,iv:7utb9R1MK9HC0403+S0kpJ2lPIkP9THfqvcZvPo0uKo=,tag:sxZAqOracEoTy65NyedRpA==,type:str]
        env:
            RESTIC_COMPRESSION: ENC[AES256_GCM,data:YmaJ,iv:IdY/Z3PRPlUyjR3vk4TGQ0uPjiie+VVZJHxqqaIhiH4=,tag:i6LqvORLWmGs48euqxA4OA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5cBh0q5mXiWhrIWmos+onTPAF46V4fZMww==,iv:WWx+OZ4mReMg25GW1WcWPZxLPOS8nn6XZrgbsO0KCNw=,tag:Z9vnYOpsGLoUsc5R6HfaTQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+CKHTlgb2ggzasnXDMMNo7dxktFbVnY7S3pPQ/Tn8A==,iv:f59h2JYwaoCfXPPqRtx9tleU3qnL4E7jtlsGv1qsEgk=,tag:tpAarW+REUI0z+Lu/DStkg==,type:str]
    base-profile:
        backup:
            host: dedi
            one-file-system: true
            exclude-caches: true
            exclude-file: excludes.txt
            no-error-on-warning: true
            schedule-permission: system
        retention:
            before-backup: false
            after-backup: true
            keep-daily: 7
            keep-weekly: 4
            keep-monthly: 6
            keep-within: 3h
            prune: false
            host: true
profiles:
    authentik:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - authentik
            schedule: daily
            source:
                - /home/ben/docker/authentik/backup
            run-before: |
                mkdir -p /home/ben/docker/authentik/backup
                pushd /home/ben/docker/authentik/backup
                . ../backup.env
                docker exec -t -e=PG{USER,PASSWORD,DATABASE} authentik-postgresql-1 pg_dumpall --clean --if-exists > database.sql
                mkdir ak_{certs,media,templates}
                docker cp -a authentik-worker-1:/media/. ./ak_media/.
                docker cp -a authentik-worker-1:/certs/. ./ak_certs/.
                docker cp -a authentik-worker-1:/templates/. ./ak_templates/.
            run-after: |
                rm -rf /home/ben/docker/authentik/backup
    discord-status:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - discord-status
            schedule: weekly
            source:
                - /home/ben/docker/discord-status/backup
            run-before: |
                mkdir -p /home/ben/docker/discord-status/backup
                pushd /home/ben/docker/discord-status/backup
                . ../.env
                docker exec -t -e=PG{USER,PASSWORD,DATABASE} discord-status-postgres-1 pg_dumpall --clean --if-exists > database.sql
            run-after: |
                rm -rf /home/ben/docker/discord-status/backup
    ca-zeppelin:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - ca-zeppelin
            schedule: daily
            source:
                - /home/ben/docker/CA_zeppelin/backup
            run-before: |
                mkdir -p /home/ben/docker/CA_zeppelin/backup
                pushd /home/ben/docker/CA_zeppelin
                set -o allexport
                . ./.env

                docker compose -f docker-compose.ben.yml exec -t \
                  -e MYSQL_PWD=$DOCKER_PROD_MYSQL_ROOT_PASSWORD \
                  mysql \
                  mysqldump --all-databases --opt > /home/ben/docker/CA_zeppelin/backup/database.sql
            run-after: |
                rm -rf /home/ben/docker/CA_zeppelin/backup
    mailcow:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - mailcow
            schedule: daily
            source:
                - /home/ben/docker/mailcow/backup
            run-before: |
                mkdir -p /home/ben/docker/mailcow/backup
                pushd /home/ben/docker/mailcow

                MAILCOW_BACKUP_LOCATION=/home/ben/docker/mailcow/backup \
                  /home/ben/docker/mailcow/helper-scripts/backup_and_restore.sh backup all --delete-days 1
            run-after: |
                rm -rf /home/ben/docker/mailcow/backup
    traefik:
        use:
            - b2-cloud
            - base-profile
        backup:
            tag:
                - traefik-dedi
            schedule: monthly
            source:
                - /home/ben/docker/traefik
    prune:
        use:
            - b2-cloud
        prune:
            schedule: monthly
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-28T05:18:46Z"
    mac: ENC[AES256_GCM,data:XXGQ7etgPZCD4gWYkL48X73Nv6+kRfHSaGvsd/K5fHQn0apeLHHqjeM9NqOkzwnLuqf/8M5OifJMW8V+5E8BNsCd6foSOeFjKd2hON+wlM3f1OJ48EStTOFayWWZkbZw456fcUfpeP6FEDTNg1z9HOI76YM1xmP/f2/PBJ7Ud9g=,iv://HZTWSU7dhYUSzIHyRSK1WiAN5mAO6TWPqozirlCaI=,tag:tPZrIMDm6uKHvd3qh/pZmQ==,type:str]
    pgp:
        - created_at: "2025-01-28T00:39:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dlw80gGBdP4gSAQdA3KIYqNNL+OFxtuESisjSLA/lcAzsRznvfum6AZ07kgAw
            0cHg/1ZREgUeOPkCDfE+M+ELpI+CbBadG+ex2TpW/fvFHb1kt1myK8FWQMu/ycL7
            1GgBCQIQVcsnp0DGNqbb1eWnfcEyTmKHyWHRO+vC2AhLDEiI4RNW15aViowcvnKJ
            tsDYqMTKDeUmsy6A4yv4x94fJfgJ4bzVRRgPnz0JbNWI0TPIZlUWnUJ51nDzBHZ3
            lSqNfvd3drzBqg==
            =vg7W
            -----END PGP MESSAGE-----
          fp: 870F7C2D9D9AE8E302DAFF821B90D025DC9A8E35
    encrypted_regex: (env)|(repo)
    version: 3.9.4
